name: ms-mlops-py39
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip
  - pip:
    - pandas==1.5.3
    - pytest
    - scikit-learn==1.3.2
    - numpy
    - pipreqs
    - mlflow==2.7.1
    - mlflow-skinny==2.7.1
    - databricks-cli
    - azureml-mlflow
