name: ms-mlops-py39
channels:
  - conda-forge
dependencies:
  - python=3.9
  - pip
  - pip:
    # Core packages (from your working environment)
    - mlflow==3.1.4
    - pandas==2.3.1
    - scikit-learn==1.6.1
    
    # Azure ML integration
    - azureml-mlflow==1.54.0
    - azureml-defaults==1.54.0
    
    # Deployment support
    - inference-schema[numpy-support]==1.5.1