name: xray-training-cpu
channels:
  - conda-forge
  - pytorch
dependencies:
  - python=3.10
  - pip
  - numpy
  - pandas
  - scikit-learn
  - pillow
  - pytorch=2.1.*=cpu*
  - torchvision=0.16.*=cpu*
  - torchaudio=2.1.*=cpu*
  - pip:
      - mlflow<2.8
      - azureml-mlflow
      - torchxrayvision
