
name: xray-training-cpu
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - numpy=1.26.4
  - pandas
  - scikit-learn
  - pillow
  - scikit-image
  - imageio
  - tqdm
  - requests
  - pip:
      - --extra-index-url https://download.pytorch.org/whl/cpu
      # PyTorch 2.2.x (CPU)
      - torch==2.2.2
      - torchvision==0.17.2
      - torchaudio==2.2.2
      # MLflow (cliente <2.8 para evitar /logged-models)
      - mlflow==2.7.1
      - azureml-mlflow==1.61.0.post1
      # Resto de tu stack
      - pydicom
      - torchxrayvision
