$schema: https://azuremlschemas.azureedge.net/latest/commandJob.schema.json
type: command

code: src/model

command: >-
  python train.py
  --training_data ${{inputs.training_data}}
  --reg_rate ${{inputs.reg_rate}}

inputs:
  training_data:
    type: uri_folder
    path: azureml:diabetes-prod-folder:1
  reg_rate: 0.1

environment: azureml:AzureML-sklearn-0.24-ubuntu18.04-py37-cpu@latest
compute: azureml:cpu-cluster

experiment_name: diabetes-training-prod
display_name: diabetes-training-prod

description: Training diabetes model (PROD) from GitHub Actions
